# Generated by Django 5.2.17 on 2026-09-23 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorieObjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "catégorie d'objet",
                "verbose_name_plural": "catégories d'objets",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Comite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=150, unique=True, verbose_name="nom"),
                ),
            ],
            options={
                "verbose_name": "comité",
                "verbose_name_plural": "comités",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="CompteurRecu",
            fields=[
                (
                    "annee",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="année"
                    ),
                ),
                (
                    "dernier_numero",
                    models.PositiveIntegerField(
                        default=0, verbose_name="dernier numéro attribué"
                    ),
                ),
            ],
            options={
                "verbose_name": "compteur de reçus",
                "verbose_name_plural": "compteurs de reçus",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="Donateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="adresse"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code postal doit contenir exactement 5 chiffres.",
                                regex="^\\d{5}$",
                            )
                        ],
                        verbose_name="code postal",
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "consentement_rgpd",
                    models.BooleanField(
                        default=False, verbose_name="consentement RGPD"
                    ),
                ),
                (
                    "date_consentement",
                    models.DateTimeField(verbose_name="date du consentement"),
                ),
                (
                    "accepte_contact",
                    models.BooleanField(
                        default=False, verbose_name="accepte d'être recontacté"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "donateur",
                "verbose_name_plural": "donateurs",
                "ordering": ["nom", "prenom"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("consentement_rgpd", True)),
                        name="donateur_consentement_rgpd_obligatoire",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Epicerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                ("adresse", models.CharField(max_length=255, verbose_name="adresse")),
                (
                    "code_postal",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code postal doit contenir exactement 5 chiffres.",
                                regex="^\\d{5}$",
                            )
                        ],
                        verbose_name="code postal",
                    ),
                ),
                ("ville", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Utilisé dans l'adresse du formulaire : /don/<identifiant>/. Ne pas modifier une fois le QR code imprimé.",
                        max_length=80,
                        unique=True,
                        verbose_name="identifiant d'URL",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "comite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epiceries",
                        to="dons.comite",
                        verbose_name="comité",
                    ),
                ),
            ],
            options={
                "verbose_name": "épicerie",
                "verbose_name_plural": "épiceries",
                "ordering": ["comite__nom", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Don",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeton",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="jeton public",
                    ),
                ),
                (
                    "date_don",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date du don",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DECLARE", "Déclaré"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="DECLARE",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "donateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dons",
                        to="dons.donateur",
                        verbose_name="donateur",
                    ),
                ),
                (
                    "epicerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dons",
                        to="dons.epicerie",
                        verbose_name="épicerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "don",
                "verbose_name_plural": "dons",
                "ordering": ["-date_don"],
            },
        ),
        migrations.CreateModel(
            name="LigneDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="description"
                    ),
                ),
                (
                    "quantite",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("NEUF", "Neuf"),
                            ("BON_ETAT", "Bon état"),
                            ("USAGE", "Usagé"),
                            ("A_REPARER", "À réparer"),
                        ],
                        max_length=10,
                        verbose_name="état",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="dons.categorieobjet",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "don",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="dons.don",
                        verbose_name="don",
                    ),
                ),
            ],
            options={
                "verbose_name": "objet donné",
                "verbose_name_plural": "objets donnés",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "sequence",
                    models.PositiveIntegerField(verbose_name="numéro dans l'année"),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="numéro de reçu"
                    ),
                ),
                (
                    "date_emission",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="émis le"
                    ),
                ),
                (
                    "email_envoye",
                    models.BooleanField(default=False, verbose_name="email envoyé"),
                ),
                (
                    "don",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recu",
                        to="dons.don",
                        verbose_name="don",
                    ),
                ),
            ],
            options={
                "verbose_name": "reçu",
                "verbose_name_plural": "reçus",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="epicerie",
            constraint=models.UniqueConstraint(
                fields=("comite", "nom"), name="epicerie_nom_unique_par_comite"
            ),
        ),
        migrations.AddConstraint(
            model_name="don",
            constraint=models.CheckConstraint(
                condition=models.Q(("statut__in", ["DECLARE", "VALIDE", "ANNULE"])),
                name="don_statut_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignedon",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantite__gte", 1)), name="lignedon_quantite_min_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="lignedon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("etat__in", ["NEUF", "BON_ETAT", "USAGE", "A_REPARER"])
                ),
                name="lignedon_etat_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="recu",
            constraint=models.UniqueConstraint(
                fields=("annee", "sequence"), name="recu_annee_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="recu",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="recu_sequence_min_1"
            ),
        ),
    ]
