# Generated by Django 5.2.17 on 2026-09-23 12:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lignedon",
            name="lignedon_quantite_min_1",
        ),
        migrations.AddField(
            model_name="don",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True, verbose_name="validé le"),
        ),
        migrations.AddField(
            model_name="don",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dons_valides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validé par",
            ),
        ),
        migrations.AlterField(
            model_name="lignedon",
            name="description",
            field=models.CharField(max_length=200, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="lignedon",
            name="quantite",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="quantité",
            ),
        ),
        migrations.AddConstraint(
            model_name="don",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("statut", "VALIDE"), _negated=True),
                    ("date_validation__isnull", False),
                    _connector="OR",
                ),
                name="don_valide_a_une_date_validation",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignedon",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantite__gte", 1), ("quantite__lte", 99)),
                name="lignedon_quantite_entre_1_et_99",
            ),
        ),
    ]
