# Generated by Django 5.2.17 on 2026-09-29 08:17
#
# Ajoute l'icône des catégories, puis la remplit pour les catégories qui
# existent déjà en base (sans écraser une icône déjà choisie).

from django.db import migrations, models

ICONES_PAR_DEFAUT = {
    "Mobilier": "🛋️",
    "Électroménager": "🔌",
    "Vêtements": "👕",
    "Chaussures": "👟",
    "Linge de maison": "🛏️",
    "Vaisselle": "🍽️",
    "Jouets": "🧸",
    "Livres": "📚",
    "Puériculture": "🍼",
    "Informatique": "💻",
    "Hygiène": "🧼",
    "Alimentaire": "🥫",
    "Autre": "📦",
}


def remplir_icones(apps, schema_editor):
    CategorieObjet = apps.get_model("dons", "CategorieObjet")
    for nom, icone in ICONES_PAR_DEFAUT.items():
        CategorieObjet.objects.filter(nom=nom, icone="").update(icone=icone)


class Migration(migrations.Migration):

    dependencies = [
        ("dons", "0002_validation_description_quantite_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorieobjet",
            name="icone",
            field=models.CharField(blank=True, max_length=8, verbose_name="icône"),
        ),
        # Retour arrière possible : on ne fait rien (la colonne est supprimée)
        migrations.RunPython(remplir_icones, migrations.RunPython.noop),
    ]
