# Generated by Django 5.2.17 on 2026-09-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dons", "0003_categorie_icone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorieobjet",
            name="icone",
        ),
    ]
